// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 6/27/2026, 12:13:07 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
import cfg3 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/marquis/curatewithng/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/plugins/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/admin/composables/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/admin/utils/**/*.{js,ts,mjs}","/Users/marquis/curatewithng/admin/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/marquis/curatewithng/admin/app.config.{js,ts,mjs}"]}},
{},
cfg2,
cfg3
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;